export default [{
  icon: 'alert',
  bgcolor: '#2d8cf0',
  title: '一级响应',
  counter: 'loading',
  href: '/index/findall',
  status: 'first'
}, {
  icon: 'alert',
  bgcolor: '#f90',
  title: '二级响应',
  counter: 'loading',
  href: '/index/findall',
  status: 'second'
}, {
  icon: 'alert',
  bgcolor: '#ed3f14',
  title: '三级响应',
  counter: 'loading',
  href: '/index/findall',
  status: 'third'
}, {
  icon: 'help',
  bgcolor: '#e9eaec',
  title: '待审核',
  counter: 'loading',
  href: '/index/check',
  status: 'pending'
}, {
  icon: 'checkmark',
  bgcolor: '#19be6b',
  title: '进行中',
  counter: 'loading',
  href: '/index/findall',
  status: 'progress'
}, {
  icon: 'close',
  bgcolor: '#555',
  title: '历史记录',
  counter: 'loading',
  href: '/index/history',
  status: 'history'
}]
